HW9 Tests
DmitriyBabii/A-level-DmitriyBabii pull request #5
Opened 2021-11-19 16:46 UTC by DmitriyBabii

2021-11-20 22:55 UTC, Fabolo12 requested changes
Ok, but I want to see the use of Mocks.
Refactor 
```
task5(Scanner in) {
...
}
```
and in tests create a mock scanner

2021-11-20 22:55 UTC, Fabolo12 commented on src/test/java/com/alevel/cw3/MainTest.java
> +    }
It is better to write one test for each type of operation

2021-11-21 22:02 UTC, DmitriyBabii commented
Can`t mock Scanner because it final

2021-11-22 00:18 UTC, Fabolo12 approved these changes
10

2021-11-22 00:18 UTC, Fabolo12 commented on src/test/java/com/alevel/cw3/MainTest.java
> +    }
This is a misuse of mock, it must be passed to the method

2021-11-22 00:18 UTC, Fabolo12 commented on src/test/java/com/alevel/cw3/MainTest.java
> +    }
This is the correct use of mock

2021-11-22 00:21 UTC, Fabolo12 commented on src/test/java/com/alevel/cw3/MainTest.java
> +        InputOutput in = Mockito.mock(InputOutput.class);
You can simplify the code if you write like this
![image](https://user-images.githubusercontent.com/18196757/142785049-09f95aa5-b897-4781-8cd2-410d37da5643.png)

2021-11-22 00:45 UTC, merged